ifneq ($(NEHE_CAPTURE_FIXED_TIME_MS),)
CFLAGS += -DNEHE_CAPTURE_FIXED_TIME_MS=$(NEHE_CAPTURE_FIXED_TIME_MS)
endif

ifneq ($(NEHE_PERF_OVERLAY),)
CFLAGS += -DNEHE_PERF_OVERLAY=$(NEHE_PERF_OVERLAY) -DNXGL_PERF_OVERLAY=$(NEHE_PERF_OVERLAY)
endif
